name: Deploy with gh-pages

on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - uses: actions/setup-node@v1
      with:
       node-version: 16.x
    - name: Setup NPM
      run: |
        npm install
    - name: Deploy
      run: |
        npm run deploy
        git subtree split -b gh-pages -P build/
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git stash
        git checkout gh-pages
        git add -A
        git commit -m "Github Pages"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
