name: Deploy with gh-pages

on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - name: Deploy
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/simplebinary.github.io.git
        npm run deploy -- -u "Github Actions <support+actions@github.com>" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
